### ISSUE TITLE
Always "ImportError: No module named password"

### ISSUE THREAD

**Issue by lasse79** [NickWaterton/Roomba980-Python#26]
Hi 
i tried to follow the hoe to do now several time on serveral systems. But all of them was debian on a raspberryPI3 Hardware. Maybe someknow the issue or can support me, or maybe a generel failure now?

I tried the pip installtion and as well the git, after executing the script i always getting some errrors connected to a password module.
```
> python roomba.py`
Traceback (most recent call last):
File "roomba.py", line 25, in <module>
from roomba.password import Password
File "/root/Roomba980-Python/roomba/roomba.py", line 25, in <module>
from roomba.password import Password
ImportError: No module named password
```

```
> python getpassword.py
Traceback (most recent call last):
File "getpassword.py", line 12, in <module>
from roomba import Password
File "/root/Roomba980-Python/roomba/roomba.py", line 25, in <module>
from roomba.password import Password
ImportError: No module named password
```
Had somebody the same issue and fixed it?

Thanks

**Comment by NickWaterton** [comment]
Did you run `sudo python setup.py install` Then you execute by simply entering `roomba`

The original instructions were written for before the script was packaged for pypi. The script now expects the library to be installed, which is why it’s not found - you haven’t installed it.

The next issue on the RPi3 is that you need opencv installed (it’s one of the pypi requirements), and you can’t install it via pip (don’t know why). You have to build it as described here
[https://www.pyimagesearch.com/2016/04/18/install-guide-raspberry-pi-3-raspbian-jessie-opencv-3/](url)

I need to revisit this whole thing, but I didn’t package it for pypi, so I don’t know what exactly changed since I posed the original.

**Comment by NickWaterton** [comment]
Actually, just tried this and it still doesn’t work on a RPi3 (which I have lying around).

I suggest, for now you edit roomb.py, line 25.
`from roomba.password import Password`

And change it to
`from password import Password`

Hopefully that should fix it.
The problem is that the script now expects to be installed, but on an RPi one of the dependencies is opencv-python (which would normally be automatically installed via pip), but this doesn’t work on RPi, so the script doesn’t complete installation, so it can’t find the installed module “roomba”.

Let me know if this works, and I’ll see if I can fix it.

Not keen on the whole pypi thing, it sort of makes it easy to install, but it sure messes thing up cross platform...

**Comment by NickWaterton** [comment]
No, just tried that, and seems there are problems if you don’t have opencv or pillow installed, neither of which install properly via pip on an RPi.

Also, if you can’t install the program (because of the RPi pip issues), the program is __main__.py not roomba.py, roomba.py is the library which is supposed to be installed, __main__.py gets copied to roomba when it’s installed properly.

Looks like there is some work to be done to get this to work on a RPi, sorry I never tested it on an RPi before. Should not be much to do. I’ll see what Avi can do.
